version: "3"

services:
  miservicio_mysql:
    image: mysql:5.7
    build: ./DB
    environment:
      - MYSQL_DATABASE=CLIENTE
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
  
  miservicio_backend:
    restart: always
    build: ./Backend
    container_name: 'miservicio_backend'
    expose:
      - 80
    ports:
      - 80:3000
    volumes:
      - ./Backend:/backend  
   
    links: 
      - miservicio_mysql