version: "3"

  
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=DBTEST
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./src/Script/data.sql:/docker-entrypoint-initdb.d/1.sql 
    ports:
      - '3306:3306'


  miservicio_backend:
    restart: always
    build: ./Backend
    container_name: 'miservicio_backend'
    expose:
      - 80
    ports:
      - 80:3000
    volumes:
      - ./Backend:/backend  
   
    links: 
      - mysql